### ISSUE TITLE
documentation with an example

### ISSUE THREAD

**Issue by hartenthaler** [Jefferson49/RepositoryHierarchy#14]
Your module is a very powerful tool! The documentation in the README is precise but abstract.

For me it would help if you could give an example of how to use it, for example:
- define a repository (meta repository) Matricula
- define a persona "Maria Maier" and a related source for her birth event, found in Matricula.
- show how you would store the source citation, the source, the image of the source, and the linked repository

I would like to see the GEDCOM code behind it so that I can arrange it so that the structure of the sources and repositories in my tree follows your example. Up to now I was able to instal and see your webtrees module but did not get it productive because I wasn't able to use the call numbers in the right way.

**Comment by Jefferson49** [comment]
Thank you for the useful feedback. I have just added an additional chapter to the Readme file, which contains links to a demo website and examples with some GEDCOM snippets.

**Comment by hartenthaler** [comment]
This is very helpful. Thank you! What is the relation of repository R1 to the other repositories? I have to read the concept of the Meta repositories more carefully. And I will play with your demo site! This will show it.

**Comment by Jefferson49** [comment]
In the provided example, R1 is the base repository, R8773 the meta repository, and R7328 just some other repository. 

I have also included some more description in the example of the Readme file.

**Comment by hartenthaler** [comment]
Thank you! I have to play with that now.
