### ISSUE TITLE
Error when opening the menu topic "Lists" / "Repository Hierarchy" 

### ISSUE THREAD

**Issue by hartenthaler** [Jefferson49/RepositoryHierarchy#15]
When opening the menu topic "Lists" / "Repository Hierarchy" I get an error:
> fopen(…/modules_v4/repository_hierarchy/resources/caln/R1.php): Failed to open stream: No such file or directory …/modules_v4/repository_hierarchy/CallNumberCategory.php:390
> #0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
> #1 …/modules_v4/repository_hierarchy/CallNumberCategory.php(390): fopen()
> #2 …/modules_v4/repository_hierarchy/RepositoryHierarchy.php(1416): Jefferson49\Webtrees\Module\RepositoryHierarchyNamespace\CallNumberCategory::saveC16YFile()

**Comment by Jefferson49** [comment]
Thank you for reporting the issue. 

The reason for this error is that there should exist an empty folder "modules_v4\repository_hierarchy\resources\caln", in which the module saves files for call number descriptions. This empty "caln" folder exists in my local Git. However, I just learned that Git does not synchronize empty folders to Github. 

As a workaround, you can create an empty "caln" folder in the described path.

I will include an empty ".gitkeep" file in the "caln" folder and create a new release soon.

**Comment by Jefferson49** [comment]
Fixed with releases v1.2.2
