### ISSUE TITLE
PHP error: Undefined array key "S4"

### ISSUE THREAD

**Issue by hartenthaler** [Jefferson49/RepositoryHierarchy#31]
... using version 1.3.0
```
Undefined array key "S4" …/modules_v4/repository_hierarchy/RepositoryHierarchy.php:1483
#0 …/modules_v4/repository_hierarchy/RepositoryHierarchy.php(1483): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
#1 …/app/Http/Middleware/RequestHandler.php(55): Jefferson49\Webtrees\Module\RepositoryHierarchyNamespace\RepositoryHierarchy->handle()
#2 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()

```
![Screenshot (384)](https://github.com/Jefferson49/RepositoryHierarchy/assets/6324175/b5b5ab1e-3c97-4e5d-b8f2-86f2dba95465)

**Comment by Jefferson49** [comment]
Thank you for reporting the issue!

My hypothesis is that the error occurs for sources without a call number. Can you check if the source "S4" has no call number?

If my assumption is right, you can check if the following patched version of the RepositoryHierarchy.php file solves the issue.

[RepositoryHierarchy.php.zip](https://github.com/Jefferson49/RepositoryHierarchy/files/12233961/RepositoryHierarchy.php.zip)

**Comment by hartenthaler** [comment]
Your hypothesis was correct and the patched version solves the issue. Perfect!
