### ISSUE TITLE
Better formatting of REPO sub records

### ISSUE THREAD

**Issue by WGroleau** [Jefferson49/RepositoryHierarchy#32]
Maybe this should be two issues, but …
1. Suggest making the REPO display within a SOUR a "collapsible" item.
2. Omit fields that are blank.
![temp](https://github.com/Jefferson49/RepositoryHierarchy/assets/5910274/18bbf177-0af4-43ee-9c45-c95b30e07cae)

**Comment by Jefferson49** [comment]
Thank you very much for the feedback!

I worked on an improvement. Now, it looks like the attached screenshots. Does this meet the intended improvements?

**Collapsible with call numbers:**
![screenshot_source_citation_in_webtrees](https://github.com/Jefferson49/RepositoryHierarchy/assets/81484983/5fe9516a-6b8d-4105-8842-b18be7c3604d)

**Without call number:**
![No CALN](https://github.com/Jefferson49/RepositoryHierarchy/assets/81484983/acf55ddd-a07f-419c-9534-bde3408e05da)

**Comment by WGroleau** [comment]
That looks great.  I’m copying in the changed files to test it.  I'm surprised how many files were affected.

**Comment by Jefferson49** [comment]
Well, I do not know what exactly happened. Before your answer, the code was still on my local computer and not synched to Github.

I have now synched the latest code with commit [1ef7029](https://github.com/Jefferson49/RepositoryHierarchy/commit/1ef7029360c399c9c6d17e674ecb105b923b62d6). If you download the main branch, you should be able to test it.

**Comment by Jefferson49** [comment]
Completed with [1ef7029](https://github.com/Jefferson49/RepositoryHierarchy/commit/1ef7029360c399c9c6d17e674ecb105b923b62d6)

**Comment by WGroleau** [comment]
Yes, I see it now with the download labeled 1.3.3
