### ISSUE TITLE
Show media objects of sources, which are referenced within a source citations

### ISSUE THREAD

**Issue by Jefferson49** [Jefferson49/RepositoryHierarchy#37]
In the webtrees forum, there was a discussion to show media objects of sources, which are itself referenced within a source citations: https://www.webtrees.net/index.php/en/forum/help-for-release-2-1/38268-sources-tab

**Comment by Jefferson49** [comment]
The enclosed file includes a simple patch to test this feature. The enclosed file needs to replace the corresponding file in release v1.3.4

[source-facts-within-citation.zip](https://github.com/Jefferson49/RepositoryHierarchy/files/12640373/source-facts-within-citation.zip)

**Comment by KurtRo58** [comment]
Thank you for your efforts, I replaced the file, unfortunately I didn't get the desired result. Everything looks unchanged.

**Comment by Jefferson49** [comment]
It only seems to work for citations within facts/events and not for citations directly linked to the individual. Can you confirm this with your data?

Unfortunatelly, the code for citations linked to individuals is beyond the scope I can modify with my custom module. Therefore, this would need to be changed by webtrees.

**Screenshot of citations within facts (here: occupation) => this seems to work:**

![screenshot_media_objects_of_sources](https://github.com/Jefferson49/RepositoryHierarchy/assets/81484983/acdfea41-b748-4364-ade2-cb357b923c5d)

**Screenshot of citations directly linked to individual => no media objects shown:**

![screenshot_sources_with_media_object 2](https://github.com/Jefferson49/RepositoryHierarchy/assets/81484983/5034556e-8f0b-4d22-a523-9016624508d6)

**Comment by KurtRo58** [comment]
Yes I can confirm that
![image](https://github.com/Jefferson49/RepositoryHierarchy/assets/5472618/ffbbac5a-2fb4-44e7-b3ad-2f45f0cdaa76)

**Comment by Jefferson49** [comment]
Thanks for checking. However, the screenshot does not show any sources at all (?)

**Comment by KurtRo58** [comment]
Here is one with a source.
![image](https://github.com/Jefferson49/RepositoryHierarchy/assets/5472618/b577de65-9234-4944-b913-40925801afec)

**Comment by Jefferson49** [comment]
o.k., this shows that the code in the patch would work for source citations in facts/events (like in occupation).

In order to get an overview about your 8000 source citations (or sources), you could do a quick search in your latest Gedcom export. Search for "@ SOUR", "1 SOUR" and "2 SOUR" (e.g. with notepad++) and count the number of hits. "@ SOUR" would count the number of sources. "1 SOUR" would deliver an estimate, how many source citations are assigned directly to an individual or a family. "2 SOUR" could be properly handled with the code in the patch.

**Comment by Jefferson49** [comment]
If you have some programming skills and have the confidence to patch your Gedcom, it would be possible to write a skript (e.g. with Python, using regular expressions) to convert the "1 SOUR" citations. You could create a list of all sources and the related media objects in your Gedcom file. Afterwards, you could search all "1 SOUR" citations and add the related media objects from the sources/media list.

If you are interested, I can provide some code snippets as a starting base.

**Comment by KurtRo58** [comment]
Thank you for your offer, I'll try the Gedcom service program from Hesmer, I've had good experiences with it.

**Comment by Jefferson49** [comment]
Very good idea! I am also using the Gedcom Service Programs a lot.
