### ISSUE TITLE
Dependency on HitCountFooterModule

### ISSUE THREAD

**Issue by ric2016** [Jefferson49/RepositoryHierarchy#39]
The functionality "copy/paste mechanism for source citations in the individual and family view" requires the 'Hit counters' footer module to be enabled (additionally, the tree preference "Hit counters" must be set to "show"), otherwise the copy icon isn't displayed.

This is caused by checking specific session parameters, [here](https://github.com/Jefferson49/RepositoryHierarchy/blob/ce30d10832a79327011df9e2dfd8fe57011660ef/resources/views/fact-gedcom-fields.phtml#L31) and a few lines later. These session parameters are only set in the 'Hit counters' footer module, [here](https://github.com/fisharebest/webtrees/blob/f71a4582d9293d3d97b8d184ace53b195360ebec/app/Module/HitCountFooterModule.php#L194).

The easiest way to remove this dependency is probably to duplicate these Session parameters under different names and set them within the custom module.

**Comment by Jefferson49** [comment]
Thank you for this important hint to the dependency. 

The background is that I was facing difficulties to get the context of a fact's gedcom to be shown with "fact-gedcom-fields.phtml". In fact-gedcom-fields.phtml, only the Gedcom and the parent tags are handed over and it is not known to which individual or family they belong. The mentioned session parameters are a nice workaround to get this context information, but I agree that there should not be a dependency.

At the moment, I do not know how to solve this. I will check  the  'Hit counters' footer module and try to learn how it sets the session variables. Maybe, I can use a simular approach.
