### ISSUE TITLE
Typo in repository label

### ISSUE THREAD

**Issue by ric2016** [Jefferson49/RepositoryHierarchy#8]
Hallo Markus, das Modul sieht sehr nützlich aus!

Kleiner Fehler [hier im Label](https://github.com/Jefferson49/RepositoryHierarchy/blob/f25343eb55228e4780193944c257dec74ab9b059/RepositoryHierarchy.php#L595), Fix:

```
return I18N::translate('Repository Hierarchy of: %s', $repository->fullName());
```

**Comment by Jefferson49** [comment]
Hallo Richard,

danke für das positive Feedback und fürs Melden des Typos. Werde ich gleich korrigieren.
