### ISSUE TITLE
Data Fix via control panel doesn't work

### ISSUE THREAD

**Issue by ric2016** [Jefferson49/RepositoryHierarchy#9]
Selecting the data fix via "Control panel > Manage family trees > Data fixes > Repository Hierarchy" does not seem to work - maybe isn't even intended to?

Using the "Search" button leads to a data tables error. Maybe the easiest solution is to just disable the data fix here by always returning 0 results, and adding a text explaining that the data fix is to be started from elsewhere.

**Comment by Jefferson49** [comment]
Yes, it is not intended to use the data fix in the control panel. However, I have not found a mechanism. to make the data fix private to the internal use in the module. 

As a workaround, I have already put some code in the "fixOptions" method to return empty options. By this means, the data fix can not lead to negative result. However, I agree that it is still confusing for the user.

I will check if I can put some simular code in the other data fix methods to avoid the effect.

**Comment by Jefferson49** [comment]
Now, I managed to include an error text if the data fix is called in the "control panel"
